import type { NextPage } from 'next'
import Head from 'next/head'
import styles from '../styles/Home.module.css'
import DynamicRoutingLink from '../components/DynamicRoutingLink'

const pageNum = [1, 2, 3, 123, 44, 6, 1235];

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>practice NextJs</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <h2>넥스트 JS 실행 확인</h2>
        <a href='/about'>About 페이지 이동</a>
        <div className={styles.dynamicBox}>
          {pageNum.map(el => <DynamicRoutingLink key={el} page={ el } />) }
        </div>
      </main>
      <footer className={styles.footer}>
        Footer
      </footer>
    </div>
  )
}

export default Home
